name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
  ## What’s Changed
  $CHANGES
categories:
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📖 Documentation
    label: docs
  - title: 📦 Dependency updates
    label: dependencies
